name: pharma_connect
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.4
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  go_router: ^14.8.0
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4
  connectivity_plus: ^6.1.3
  firebase_core: ^3.12.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  injectable_generator: ^2.7.0
  freezed: ^2.5.8
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true